### PR TITLE
Feat/board utils

### PR DESCRIPTION
**Pull request by etienne-85**

### CODE REVIEW

**Comment by etienne-85** [comment]
> Those functions looks quite low level, they will need to be used by the server ? The sdk should be used to provide user/service facing functions, `get_board_bounds` seems alright, but `find_split_axis` ? the server would rather use a `get_board_data` which contains bounds, holes, start positions, etc

Tthis is what we spoke during previous call, finding start pos wasn't really related to world but more to game logic.
Ideally this would be more appropriate to be placed dapp, but as long as server also need that information it must be in common package.
The `find_split_axis` is used to divide board in two side which is required for generating both player's positions.

**Review by Sceat — APPROVED** [review]

**Review by Sceat — APPROVED** [review]

**Review by Sceat — APPROVED** [review]

**Review by Sceat — APPROVED** [review]
/merge

**Review by Sceat — APPROVED** [review]

**Pull request merged**
